spring:
    datasource:
        url: jdbc:mysql://localhost:3306/Hoyoverse
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
#            naming:
#                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            ddl-auto: update

application:
    security:
        jwt:
            secret-key: 52ba140d618ec4e1cfa9d9b73d4d8d9926c05318ef0a02b3510d0a18e9d78034
            expiration: 300000 # 5 minutes
            refresh-token:
                expiration: 604800000 # 7 days